### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [vasco-santos/set-delayed-interval#3]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by vasco-santos** [comment]
Hey @geopic 
Thanks for reaching out. I am thinking on leveraging the [aegir support with jsdocs](https://github.com/ipfs/aegir#jsdoc-typescript-support) for this. The goal here would be to create the typescript declaration files automatically on release, by the jsdoc. I will check if we can go with this once I have some spare time

**Comment by geopic** [comment]
Sounds great. If there's any way I can help in the process, just let me know :smile:
